### ISSUE TITLE
Should Superforms & Zod really be installed as devDependencies?

### ISSUE THREAD

**Issue by LorisSigrist** [ciscoheat/superforms-web#18]
The [Get Started](https://superforms.rocks/get-started) guide instructs users to install the library as a devDependency.
```bash
(p)npm i -D sveltekit-superforms zod
````
Both zod and superforms are still around at runtime, so shouldn't they be regular dependencies instead? (remove the `-D`). This is unlikely to ever actually cause any issue in an app, it's just a little unidiomatic.

**Comment by ciscoheat** [comment]
They are both bundled in the end, and have no extra runtime components that must be deployed (like [sharp](https://sharp.pixelplumbing.com/)), so there is basically no difference. Some hosting platforms don't install devDependencies in the final output, making the build a bit faster and cleaner.
