### ISSUE TITLE
Update Generics documentation

### ISSUE THREAD

**Issue by Skylli202** [ciscoheat/superforms-web#22]
As discussed in this [issue](https://github.com/ciscoheat/sveltekit-superforms/issues/245) of the library repository. Svelte 4 changed the way to create `generic`, as such some example provided in the documentation needs to be updated. While the old way still works, ESLint (with the default configuration) is not happy about it.

As far as I am aware of generics are used in the following documentation pages:
- `/components#forms-and-fields-in-components`

To any contributor who think I missed a page where `generic` is used, please tell me.

> @ciscoheat This is my first contribution, feel free to correct me in the way you would like things to be done.

**Comment by ciscoheat** [comment]
Docs updated on the [components](https://superforms.rocks/components#using-a-formfieldproxy) page now.
