### ISSUE TITLE
Snapshot support doc clarification

### ISSUE THREAD

**Issue by janzheng** [ciscoheat/superforms-web#24]
Hi there,

It wasn't immediately clear to me from the docs how to support Snapshots, and I couldn't find the demo in /concepts/snapshots/ that covers how capture and restore works.. This worked as a minimal example for me. Could you kindly add this to the docs for those of us not too well-versed in snapshot?

```
const { form, capture, restore } = superForm(data.form);

  export const snapshot = { 
    capture: () => $form, 
    restore: (value) => {$form = value;} // restores the data from the snapshot
  }; // svelte-snapshot support

**Comment by ciscoheat** [comment]
Didn't the code in the docs work? It does in the tests.
