### ISSUE TITLE
Typescript violation for superValidate()

### ISSUE THREAD

**Issue by chornbec** [ciscoheat/superforms-web#7]
I'm following this [section](https://github.com/ciscoheat/superforms-web/blob/main/src/routes/get-started/%2Bpage.md#initializing-the-form-in-the-load-function) in the getting-started guide, and I received the following Typescript violation on `superValidate` for this [line](https://github.com/ciscoheat/superforms-web/blob/main/src/routes/get-started/+page.md?plain=1#L71):
```
Expected 2-3 arguments, but got 1.ts(2554)
index.d.ts(32, 154): An argument for 'schema' was not provided.
```

Shouldn't that line be something like this for empty forms instead?
```
const form = await superValidate({}, schema);
```

**Comment by ciscoheat** [comment]
Hello, sorry, I missed this issue, didn't monitor this repo so closely. :) The later versions handles a call to `superValidate` with only the schema, so it should definitely work if you update.

**Comment by chornbec** [comment]
Thanks,
I verified that v0.8.7 works and I don't need to specify two arguments for `superValidate()`.
