### ISSUE TITLE
Minor mistake with $allErrors documentation

### ISSUE THREAD

**Issue by zerosym** [ciscoheat/superforms-web#8]
Conditional should check the length of the array.

https://superforms.vercel.app/concepts/error-handling#listing-errors

https://github.com/ciscoheat/superforms-web/blob/5f465da7584a819ecfc02f1ee7aecb066e38e68b/src/routes/concepts/error-handling/%2Bpage.md?plain=1#L122

https://github.com/ciscoheat/superforms-web/blob/5f465da7584a819ecfc02f1ee7aecb066e38e68b/src/routes/concepts/error-handling/Form.svelte#L23

**Comment by ciscoheat** [comment]
Fixed now!
